eureka:
  client:
    service-url:
      defaultZone: http://localhost:9991/eureka/
  instance:
    instance-id: city2Id

spring:
  application:
    name: city2

#开启熔断
feign:
  hystrix:
    enabled: true

